# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    env:
      NODE_ENV: development
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x, 24.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup MySQL
        run: |
          sudo systemctl start mysql
          mysql -u root -proot < db/create-db.sql
      - name: Create .env file
        run: |
          echo "DB_HOST=localhost" >> .env
          echo "DB_NAME=cicdtest" >> .env
          echo "DB_USER=jannepeh" >> .env
          echo "DB_PASS=exel80jajop" >> .env
          echo "PORT=3000" >> .env
          cat .env
      - name: Use Node.js ${{ matrix.node-version }} in ${{env.NODE_ENV}} mode
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: ls
      - run: npm run build --if-present
      - run: npm run test
      - name: Autom Apidoc
        run: npm run apidoc
      - name: Upload Apidoc artifact
        uses: actions/upload-artifact@v4
        with:
          name: apidoc-node-${{ matrix.node-version }}
          path: dcs/
